const products = [
{name:"Optical Mounts & Holders",items:["Lens Mounts","Mirror Mounts","Kinematic Mounts","Optical Posts","Post Holders","Optic Holders","Filter Mounts","Polarizer Mounts","Prism Mounts","Beam Splitter Mounts","Cylindrical Lens Mounts","Objective Mounts","Fiber Mounts","Fiber Collimator Mounts","Laser Mounts","Sensor Mounts","Optical Sensor Mounts","Camera Mounts","V-Mounts"]},
{name:"Lens Tube & Optical Tube System",items:["Lens Tubes","Retainer Rings","Extender Rings","Spacer Rings","Tube Couplers","Thread Adapters","Flange Adapters","Tube End Caps","Optical Cells"]},
{name:"Cage System",items:["Cage Rods","Cage Plates","Cage Cubes","Cage Sphere","Cage Lens Mounts","Cage Adapters","Cage Corner Connectors","Cage Translation Assemblies","Cage Angular Mounts"]},
{name:"Translation & Motion Stages",items:["Linear Translation Stages","XY Translation Stages","XYZ Translation Stages","Miniature Stages","Long Travel Stages","Rotary Stages","Rotation Mounts","Goniometers","Tip-Tilt Stages","Vertical Stages","Flexure Stages","Guide Systems","Linear Bearing Assemblies","Lead Screw Assemblies","Ball Screw Assemblies","Micrometer Heads","Linear Actuator Mounts"]},
{name:"Laser & Beam Handling",items:["Laser Diode Mounts","Laser Module Mounts","Laser Tube Mounts","Beam Steering Mounts","Beam Expander Mounts","Beam Dump Mounts","Aperture Mounts","Iris Mounts","Spatial Filter Mounts","Periscope Assemblies","Beam Height Adapters","Laser Alignment Fixtures"]},
{name:"Optical Tables, Breadboards & Plates",items:["Optical Breadboards","Breadboard Accessories","Mounting Plates","Adapter Plates","Fixture Plates","Slotted Plates","Riser Blocks","Pedestal Bases","Optical Table Clamps"]},
{name:"Precision Mechanical Components",items:["Precision Shafts","Precision Spacers","Precision Bushes","Dowel Pins","Shims","Shoulder Screws","Thumbscrews","Adjustment Screws","Locking Screws","Knobs","Threaded Rods","T-Nuts / Slot Nuts","Mounting Screws","Optical Washers"]},
{name:"Custom Opto-Mechanical Engineering",items:["Custom Optical Mounts","Custom Laser Instrument Mechanical Assemblies","Custom Aluminium Housings","Instrument Chassis","Custom Brackets","Custom Clamps","Custom Adapters","Alignment Fixtures","Assembly Fixtures","Test Fixtures","Precision CNC Components","Prototype Assemblies"]}
];
const grid=document.getElementById("productGrid");
products.forEach((group,i)=>{const card=document.createElement("article");card.className="product-card";card.innerHTML=`<span class="product-num">${String(i+1).padStart(2,"0")}</span><span class="product-arrow">↗</span><h3>${group.name}</h3><ul>${group.items.map(x=>`<li>${x}</li>`).join("")}</ul>`;grid.appendChild(card);});
document.getElementById("year").textContent=new Date().getFullYear();
const menu=document.querySelector(".menu-btn"),nav=document.querySelector(".nav");menu.addEventListener("click",()=>nav.classList.toggle("open"));document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
document.getElementById("quoteForm").addEventListener("submit",e=>{e.preventDefault();const data=new FormData(e.target);const subject=encodeURIComponent(`Quote Request - ${data.get("organisation")||"Riddhi Consultant website"}`);const body=encodeURIComponent(`Name: ${data.get("name")}\nOrganisation: ${data.get("organisation")||"Not provided"}\nEmail: ${data.get("email")}\n\nRequirement:\n${data.get("requirement")}`);window.location.href=`mailto:sales@riddhiconsultant.com?subject=${subject}&body=${body}`;});
